{{- if and .Values.auth.enabled .Values.auth.autoscaling.enabled }}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "nhost.fullname" . }}-auth
  labels:
    {{- include "nhost.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "nhost.fullname" . }}-auth
  minReplicas: {{ .Values.auth.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.auth.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.auth.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.auth.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.auth.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: {{ .Values.auth.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
