{{- if .Values.auth.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nhost.fullname" . }}-auth
  labels:
    {{- include "nhost.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
      name: http
  selector:
    {{- include "nhost.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: auth
{{- end }}
