apiVersion: v1
kind: Service
metadata:
  name: {{ include "nhost.fullname" . }}-graphql
  labels:
    {{- include "nhost.labels" . | nindent 4 }}
    app.kubernetes.io/component: graphql
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "nhost.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: graphql
