apiVersion: v1
kind: Service
metadata:
  name: {{ include "nhost.fullname" . }}-storage
  labels:
    {{- include "nhost.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "nhost.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: storage
