{{- if .Values.functions.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nhost.fullname" $ }}-functions
  labels:
{{ include "nhost.labels" $ | indent 4 }}
    app.kubernetes.io/component: functions
spec:
  accessModes:
  - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ .Values.functions.persistence.size }}
{{- end }}
