{{- if .Values.auth.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nhost.fullname" . }}-auth
  labels:
    {{- include "nhost.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
  # fixme: make this specific for different ingress controllers, such as nginx and traefik
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  {{- with .Values.global.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingress.className }}
  rules:
  - host: {{ .Values.auth.hostname }}
    http:
      paths:
      - path: /v1/auth(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ include "nhost.fullname" . }}-auth
            port:
              name: http
      paths:
      - path: /healthz(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ include "nhost.fullname" . }}-auth
            port:
              name: http
{{- if .Values.global.ingress.enableTls }}
  tls:
  - hosts:
      - {{ .Values.auth.hostname }}
    secretName: {{ include "nhost.fullname" . }}-auth-tls
{{- end }}
{{- end }}
