{{- if .Values.auth.enabled }}

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "nhost.fullname" . }}-auth-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /v1/auth

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "nhost.fullname" . }}-auth
  labels:
    {{- include "nhost.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
  {{- with .Values.global.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{- default .Values.global.ingress.hostname .Values.auth.hostname -}}`) && PathPrefix(`/v1/auth`)
    kind: Rule
    services:
    - name: {{ include "nhost.fullname" . }}-auth
      port: http
    middlewares:
    - name: {{ include "nhost.fullname" . }}-auth-stripprefix

  {{- if .Values.global.ingress.enableTls }}
  tls:
    - hosts:
      - {{ .Values.auth.hostname }}
    secretName: {{ include "nhost.fullname" . }}-auth-tls
  {{- end }}

{{- end }}
{{- end }}
