apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nhost.fullname" . }}-console
  labels:
    {{- include "nhost.labels" . | nindent 4 }}
    app.kubernetes.io/component: graphql
  annotations:
  {{- if .Values.global.dashboard.password }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ include "nhost.fullname" . }}-http
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - ok"
  {{- end }}
  {{- with .Values.global.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingress.className }}
  rules:
  - host: {{ .Values.graphql.hostnames.console }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "nhost.fullname" . }}-graphql
            port:
              name: http
{{- if .Values.global.ingress.enableTls }}
  tls:
  - hosts:
      - {{ .Values.graphql.hostnames.console }}
    secretName: {{ include "nhost.fullname" . }}-console-tls
{{- end }}
