{{- if eq .Values.global.ingress.className "nginx" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nhost.fullname" . }}-console
  labels:
    {{- include "nhost.labels" . | nindent 4 }}
    app.kubernetes.io/component: graphql
  annotations:
  {{- if .Values.global.dashboard.password }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ include "nhost.fullname" . }}-http
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - ok"
  {{- end }}
  {{- with .Values.global.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingress.className }}
  rules:
  - host: {{ default .Values.global.ingress.hostname .Values.graphql.hostnames.console }}
    http:
      paths:
      - path: /console
        pathType: Prefix
        backend:
          service:
            name: {{ include "nhost.fullname" . }}-console
            port:
              name: http
  {{- if .Values.global.ingress.enableTls }}
  tls:
  - hosts:
      - {{ default .Values.global.ingress.hostname .Values.graphql.hostnames.console }}
    secretName: {{ include "nhost.fullname" . }}-console-tls
  {{- end }}

{{- else if eq .Values.global.ingress.className "traefik" }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "nhost.fullname" . }}-console
  labels:
    {{- include "nhost.labels" . | nindent 4 }}
    app.kubernetes.io/component: graphql

  {{- with .Values.global.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ default .Values.global.ingress.hostname .Values.graphql.hostnames.console }}`) && PathPrefix(`/console`)
    kind: Rule
    services:
    - name: {{ include "nhost.fullname" . }}-graphql
      port: http
  {{- if .Values.global.dashboard.password }}
    middlewares:
    - name: {{ include "nhost.fullname" . }}-console-basic-auth
  {{- end }}

  {{- if .Values.global.ingress.enableTls }}
  tls:
    secretName: {{ include "nhost.fullname" . }}-console-tls
  {{- end }}

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "nhost.fullname" . }}-console-basic-auth
spec:
  basicAuth:
    secret: {{ include "nhost.fullname" $ }}-http
    realm: "Authentication Required - ok"

{{- end }}

