{{- if .Values.functions.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nhost.fullname" . }}-functions
  labels:
    {{- include "nhost.labels" . | nindent 4 }}
    app.kubernetes.io/component: functions
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  {{- with .Values.global.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingress.className }}
  rules:
  - host: {{ default .Values.global.ingress.hostname .Values.graphql.hostnames.api }}
    http:
      paths:
      - path: /v1/functions(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ include "nhost.fullname" . }}-functions
            port:
              name: http
{{- if .Values.global.ingress.enableTls }}
  tls:
  - hosts:
      - {{ default .Values.global.ingress.hostname .Values.graphql.hostnames.api }}
    secretName: {{ include "nhost.fullname" . }}-api-tls
{{- end }}
{{- end }}

# todo: Add ingress for traefik