apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nhost.fullname" . }}-graphql
  labels:
    {{- include "nhost.labels" . | nindent 4 }}
    app.kubernetes.io/component: graphql
  {{- with .Values.global.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingress.className }}
  rules:
  - host: {{ .Values.graphql.hostnames.api }}
    http:
      paths:
      - path: /v\d/
        pathType: Prefix
        backend:
          service:
            name: {{ include "nhost.fullname" . }}-graphql
            port:
              name: http
{{- if .Values.global.ingress.enableTls }}
  tls:
  - hosts:
      - {{ .Values.graphql.hostnames.api }}
    secretName: {{ include "nhost.fullname" . }}-api-tls
{{- end }}
