# Note that there is no nginx specific configuration here. Therefore, we do not need to explicitly care about nginx vs traefik.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nhost.fullname" . }}-graphql
  labels:
    {{- include "nhost.labels" . | nindent 4 }}
    app.kubernetes.io/component: graphql
  {{- with .Values.global.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingress.className }}
  rules:
  - host: {{ default .Values.global.ingress.hostname .Values.graphql.hostnames.api }}
    http:
      paths:
      # todo: Consider explicitly not to trigger on /v1/functions as that one is for the functions ingress.
      - path: /v1/
        pathType: Prefix
        backend:
          service:
            name: {{ include "nhost.fullname" . }}-graphql
            port:
              name: http
      - path: /v1alpha1/
        pathType: Prefix
        backend:
          service:
            name: {{ include "nhost.fullname" . }}-graphql
            port:
              name: http
      - path: /v2/
        pathType: Prefix
        backend:
          service:
            name: {{ include "nhost.fullname" . }}-graphql
            port:
              name: http
{{- if .Values.global.ingress.enableTls }}
  tls:
  - hosts:
      - {{ default .Values.global.ingress.hostname .Values.graphql.hostnames.api }}
    secretName: {{ include "nhost.fullname" . }}-api-tls
{{- end }}