{{- if .Values.migrations.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nhost.fullname" . }}-migrations
  labels:
    {{- include "nhost.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrations
  {{- with .Values.global.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.global.ingress.className }}
  rules:
  - host: {{ .Values.migrations.hostname }}
    http:
      paths:
      - path: /apis/migrate
        pathType: Prefix
        backend:
          service:
            name: {{ include "nhost.fullname" . }}-migrations
            port:
              name: http
{{- if .Values.global.ingress.enableTls }}
  tls:
  - hosts:
      - {{ .Values.migrations.hostname }}
    secretName: {{ include "nhost.fullname" . }}-migrations-tls
{{- end }}
{{- end }}
