---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nhost.fullname" $ }}-database
  labels:
{{ include "nhost.labels" $ | indent 4 }}
type: Opaque
data:
  {{ $host := .Release.Name }}
  {{ $pw := .Values.postgresql.auth.postgresPassword }}
  {{ $database := .Values.postgresql.auth.database }}
  HASURA_GRAPHQL_DATABASE_URL: {{ printf "postgres://postgres:%s@%s-postgresql/%s" $pw $host $database | b64enc }}
  POSTGRES_MIGRATIONS_SOURCE:  {{ printf "postgres://postgres:%s@%s-postgresql/%s?sslmode=disable" $pw $host  $database | b64enc }}
