{{- if .Values.global.dashboard.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nhost.fullname" $ }}-http
  labels:
{{ include "nhost.labels" $ | indent 4 }}
type: Opaque
data:
  auth: {{ htpasswd (.Values.global.dashboard.user | default "admin") .Values.global.dashboard.password | b64enc }}
{{- end }}
