{{- if .Values.global.dashboard.password }}
{{- if eq .Values.global.ingress.className "nginx" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nhost.fullname" $ }}-http
  labels:
{{ include "nhost.labels" $ | indent 4 }}
type: Opaque
data:
  auth: {{ htpasswd (.Values.global.dashboard.user | default "admin") .Values.global.dashboard.password | b64enc }}
{{- else if eq .Values.global.ingress.className "traefik" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nhost.fullname" $ }}-http
  labels:
{{ include "nhost.labels" $ | indent 4 }}
data:
  users: |1
    {{ htpasswd (.Values.global.dashboard.user | default "admin") .Values.global.dashboard.password | b64enc }}
{{- end }}
{{- end }}
