---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nhost.fullname" $ }}-smtp
  labels:
{{ include "nhost.labels" $ | indent 4 }}
    app.kubernetes.io/component: auth
type: Opaque
data:
{{- if not .Values.mailhog.enabled }}
  AUTH_SMTP_HOST: {{ .Values.auth.smtp.host | b64enc }}
  AUTH_SMTP_PORT: {{ .Values.auth.smtp.port | quote | b64enc }}
  AUTH_SMTP_USER: {{ .Values.auth.smtp.user | b64enc }}
  AUTH_SMTP_PASS: {{ .Values.auth.smtp.password | b64enc }}
  AUTH_SMTP_SENDER: {{ .Values.auth.smtp.sender | b64enc }}
{{- else }}
  {{- $host :=  include "nhost.fullname" $ }}
  AUTH_SMTP_HOST: {{ printf "%s-mailhog" $host | b64enc }}
  AUTH_SMTP_PORT: {{ "1025" | b64enc }}
  AUTH_SMTP_USER: {{ "user" | b64enc }}
  AUTH_SMTP_PASS: {{ "password" | b64enc }}
  AUTH_SMTP_SENDER: {{ "hasura-auth@example.com" | b64enc }}
  AUTH_SMTP_SECURE: {{ "false" | b64enc }}
{{- end }}
