---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nhost.fullname" $ }}-storage
  labels:
{{ include "nhost.labels" $ | indent 4 }}
    app.kubernetes.io/component: storage
type: Opaque
data:
{{- if not .Values.minio.enabled }}
  S3_ACCESS_KEY: {{ .Values.storage.s3.access_key | b64enc }}
  S3_SECRET_KEY: {{ .Values.storage.s3.secret_key | b64enc }}
  S3_ENDPOINT: {{ .Values.storage.s3.endpoint | b64enc }}
  S3_BUCKET: {{ .Values.storage.s3.bucket | b64enc }}
{{- else }}
  {{- $host :=  include "nhost.fullname" $ }}
  S3_ACCESS_KEY: {{ .Values.minio.auth.rootUser | b64enc }}
  S3_SECRET_KEY: {{ .Values.minio.auth.rootPassword | b64enc }}
  S3_ENDPOINT: {{ printf "http://%s-minio:9000" $host | b64enc }}
  S3_BUCKET: {{ "nhost" | b64enc }}
{{- end }}
