{{- $fullname := include "nhost.fullname" . -}}

---
{{- range $k, $v := .Values.graphql.migrations.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $fullname }}-{{ $v.name }}-migration"
binaryData:
{{ printf "%s: " $v.name | indent 2 }}{{($.Files.Get $v.file | b64enc )}}
{{- end }}

---
{{ if .Values.graphql.metadata.configMap}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ $fullname }}-{{ .Values.graphql.metadata.configMap.name }}-metadata"
binaryData:
{{ printf "%s: %s" .Values.graphql.metadata.configMap.name ($.Files.Get .Values.graphql.metadata.configMap.file | b64enc) | indent 2 }}
{{- end }}
